import { useEffect, useState } from 'react';
import { ApiError, searchEmails, type EmailStatus, type SearchResult } from '../api/client';
import { Pagination, StateMessage, StatusBadge } from './email-list';

const statuses: EmailStatus[] = ['SCHEDULED', 'PROCESSING', 'SENT', 'FAILED', 'CANCELLED'];

export function SearchView() {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<EmailStatus | ''>(''); const [page, setPage] = useState(1); const [results, setResults] = useState<SearchResult[] | null>(null); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [revision, setRevision] = useState(0);
  useEffect(() => { const trimmed = query.trim(); if (!trimmed && !status) { setResults(null); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { setLoading(true); setError(null); void searchEmails({ q: trimmed || undefined, status: status || undefined, page }, controller.signal).then((response) => { setResults(response.results); setTotal(response.pagination.total); }).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof ApiError ? reason.message : 'Unable to search emails.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); }, 250); return () => { controller.abort(); window.clearTimeout(timer); }; }, [query, status, page, revision]);
  const clear = () => { setQuery(''); setStatus(''); setPage(1); setError(null); };
  return <section className="mail-view"><header className="mail-toolbar"><div><h2>Search emails</h2><p>Search your indexed email records.</p></div></header><div className="search-controls"><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search recipient, subject, or message" aria-label="Search emails" /><select value={status} onChange={(event) => { setStatus(event.target.value as EmailStatus | ''); setPage(1); }} aria-label="Filter by status"><option value="">All statuses</option>{statuses.map((value) => <option value={value} key={value}>{value}</option>)}</select><button className="outline-button" type="button" onClick={clear} disabled={!query && !status}>Clear</button></div>{loading ? <div className="loading-rows" role="status"><span /><span /><span /></div> : error ? <StateMessage kind="error" message={error} action={() => setRevision((value) => value + 1)} /> : results === null ? <StateMessage kind="empty" message="Enter a search term or choose a status." /> : results.length === 0 ? <StateMessage kind="empty" message="No matching emails found." /> : <><div className="mail-table">{results.map((item) => <div className="mail-row static" key={item.emailId}><span className="recipient">To: {item.recipient}</span><StatusBadge status={item.status} time={item.sentAt ?? item.plannedSendAt} /><strong>{item.subject}</strong><span className="preview">{item.body}</span></div>)}</div><Pagination page={page} total={total} onPageChange={setPage} /></>}</section>;
}
